### ISSUE TITLE
Dynamic GeoCRS Tiles 

### ISSUE THREAD

**Issue by jlaura** [AndrewAnnex/planetcantile#1]
@AndrewAnnex Here is an example generating TMSs for planetary spherical GeoCRS dynamically. I agree, that this is going to have naming issues, but I think the logic is sound to bulk generate the needed json files.

I had to add a requests dependency to the lib, but that's trivial.

Thoughts?

https://gist.github.com/jlaura/75c6819f286d13b94458949b9df0c63d

**Comment by AndrewAnnex** [comment]
hey @jlaura, adding requests as a dependency is no problem really, but could also be solved by running wget in the github action. I like the idea of keeping this project around to run the workflow of generating the tms so that there is a single publicly available source for these files. I can easily adapt my code to work more like your gist to work from text files, were you planning to open a PR? If not is it okay for me to adapt it to this codebase? 

If you open a PR that would allow some collaborative editing, I could also open a PR but i'd have to add you to the repo, which I'm also cool with, just thinking through the options. let me know what makes the most sense to you of those

**Comment by jlaura** [comment]
@AndrewAnnex I can get a PR open that we can both work on. I wanted to see if this was inline with your thinking. I can also email with a TiTiler endpoint that we can deploy these too and test. I'd like to keep that private for now.

**Comment by AndrewAnnex** [comment]
Okay sounds good to me- Dr. Andrew AnnexOn Dec 7, 2022, at 10:00 AM, jlaura ***@***.***> wrote:﻿
@AndrewAnnex I can get a PR open that we can both work on. I wanted to see if this was inline with your thinking. I can also email with a TiTiler endpoint that we can deploy these too and test. I'd like to keep that private for now.
